# ~/.config/starship.toml

# Don't print newline
add_newline = false
[line_break]
disabled = true

# Main prompt character before input
[character]
success_symbol = "[➜](#00ff00)"
error_symbol = "[✖](bold red)"

# Directory module edits
[directory]
truncation_length = 5
truncate_to_repo = false
style = '#e5f2ae'
format = "[$path]($style) "