# ~/.config/starship.toml

# Don't print newline
add_newline = false
[line_break]
disabled = false

# Main prompt character before input
[character]
success_symbol = "[➜](#00ff00)"
error_symbol = "[✖](bold red)"

# Directory module edits
[directory]
truncation_length = 3
truncation_symbol = "~/../"
truncate_to_repo = false
style = '#e3fabe'
format = "[$path]($style) "